name: Deploy api-football-raw

on:
  push:
    branches:
      - main
    paths:
      - 'pipes/api-football-raw/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'beta'

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-football-raw ./pipes/api-football-raw

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-football-raw

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy api-football-raw-service \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-football-raw \
          --platform managed \
          --region europe-north1 \
          --concurrency 2 \
          --max-instances 2 \
          --allow-unauthenticated \
          --set-env-vars API_URL=${{ secrets.WEATHER_API_URL }},API_KEY=${{ secrets.WEATHER_API_KEY }}